#!/bin/sh

FORMAT=${1:-plain}

if [ ! -x /bin/dmesg ]; then
	echo "/bin/dmesg not exists"
	exit 1
fi

if [ ! -x /usr/bin/syslog_fc ]; then
	echo "/usr/bin/syslog_fc not exists"
	exit 1
fi

case "$FORMAT" in
	json|csv)
		/bin/dmesg -r | /usr/bin/syslog_fc -e "<%P>[%K] %M" -f ${FORMAT} -s
		;;

	*)
		/bin/dmesg
		;;
esac
